import {Geist, Geist_Mono, Vidaloka} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vidaloka = Vidaloka({
  variable: "--font-vidaloka",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Royal Studio",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vidaloka.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
